### ISSUE TITLE
Rename Service namespace to Import

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/media_mpx#136]
I just realized that we've declared a `Service` namespace such as with https://github.com/Lullabot/media_mpx/blob/8.x-1.x/src/Service/QueueVideoImports.php

mpx's API declares two types of APIs: "Data Services" (like for loading media or feeds), and "Services" (such as authentication, publishing, etc). In the `mpx-php` library, we also have a "Service" namespace: https://github.com/Lullabot/mpx-php/tree/master/src/Service

Let's rename this namespace to... something just so we aren't overloading the term. /cc @salvamomo

**Comment by salvamomo** [comment]
@deviantintegral what about `ApplicationService` (or `Application/Service` )? It conveys the fact that whatever is done in the services in that namespace, is in regards to the application / site / Drupal (e.g: queueing videos for updates doesn't make sense out of the context of the site). 

I'm proposing the "Application" prefix because that's common for this pattern of services that only get a "WhateverServiceRequest" objects, and return a "WhateverServiceResponse" object.  Command Handlers are another way of defining pretty much the same thing, so we could also move entirely out of the "Service" naming.
