### ISSUE TITLE
Import mpx video by GUID can report false positives

### ISSUE THREAD

**Issue by m4olivei** [Lullabot/media_mpx#142]
While testing the Import mpx video by GUID UI, I ran into a situation where I attempted to import a single video, the UI reported success with this message:

> The selected video has been imported.

However, the video was no where to be found. As it turns out, the guid that I was using was correctly being filtered out by a custom import event subscriber.

[From a glance at the code](https://github.com/Lullabot/media_mpx/blob/8.x-1.x/src/Service/UpdateVideoItem/UpdateVideoItem.php#L72), it appears that the submit handler for the Import mpx video by GUID UI could detect this case and report back something more informative. As it is, the message is sort of a false positive. Yes, the command was successful, but it didn't actually import anything. It looks like this would be the same problem on the Import mpx video by Full ID UI as well.

**Comment by deviantintegral** [comment]
Perhaps we could add a method to the event object for an "alteration reason". For example, if a video is skipped, it could set that message, and then both the queue worker and the UI code could display it. Then, instead of "no videos were imported as they were filtered" could be more specific like "Video <title> was skipped as it has 'exclude Drupal' set."

**Comment by m4olivei** [comment]
Ah that's interesting, great idea. In the case of no "alteration reason" we could fallback to the more generic "no videos were imported as they were filtered" message that I was suggesting.

**Comment by m4olivei** [comment]
`\Drupal\media_mpx\DataObjectImporter::importItem` would need a more complex return value. Currently it will just return an array of `\Drupal\media\MediaInterface` entities for the media that were imported. That would be a BC break 🤔

**Comment by salvamomo** [comment]
mmm, so any approach that results in changing return types of `::importItem` would be a BC break. 

This could be a good chance to split the method entirely so that it does not always call the `updateThumbnail` method after importing an item (which is a bit problematic during migrations, dev work that requires imports but not necessarily thumbnail update - this is most noticeable other side of the ocean :().  

Perhaps a similar approach to the other Services? => Service class + ServiceRequest class + ServiceResponse class:

- The request can make it optional with a flag the thumbnail bit. (plus easier to incorporate future changes without BC breaks)
- The event subscribers can throw `ItemSkipped` exceptions that the service class catches.
- The service class prepares the response object after subscribers have been processed, which has the information consumers need.

**Comment by deviantintegral** [comment]
> mmm, so any approach that results in changing return types of ::importItem would be a BC break.

Technically we aren't making any guarantees for BC yet, so we _can_ break if we want to. If we don't, we could add a new method that has the more complex return that is called by `importItem` and then `importItem` can return just the array. Probably worth doing that way given it's not that complex of a stub.

I like the idea of mirroring the other classes we've done, though I wonder if we can consolidate it all down to a set of `Import`, `ImportRequest`, and `ImportResponse` classes.

**Comment by m4olivei** [comment]
> mmm, so any approach that results in changing return types of ::importItem would be a BC break.

Right. Which, we don't have a tagged release yet, so maybe that's not that big a deal.

> Perhaps a similar approach to the other Services? => Service class + ServiceRequest class + ServiceResponse class:

Yeah I like it. I saw that you used that pattern in recent changes, I think it would work well.

Unfortunately I won't have time to do this refactoring. #143 will suite our needs for the time being.

**Comment by m4olivei** [comment]
@deviantintegral jinx buy me a coke!

**Comment by salvamomo** [comment]
> I like the idea of mirroring the other classes we've done, though I wonder if we can consolidate it all down to a set of Import, ImportRequest, and ImportResponse classes.

Yeah! Whatever the end changes, the other service classes would likely need adaptations so the purpose of each service is clear just by name 👍.
