### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by m4olivei** [Lullabot/media_mpx#171]
The tests are [currently failing](https://app.circleci.com/pipelines/github/Lullabot/media_mpx/49/workflows/d5c07180-81e9-4102-a964-733e85caa7c7/jobs/3489) due to a recent update with composer that requires any plugins that need to execute code to be explicitly allowed to do so via root config in `composer.json`:

https://getcomposer.org/doc/06-config.md#allow-plugins

Related is this open issue on Drupal.org, where the same issue is being encountered:

https://www.drupal.org/project/drupal/issues/3255749

**Comment by deviantintegral** [comment]
I totally agree that this was a BC break, at least for non-interactive terminals: https://www.drupal.org/project/drupal/issues/3255749#comment-14348693

It seems like the fix is fairly straightforward, so a PR incoming?

**Comment by m4olivei** [comment]
Well... the `allow-plugins` is a root config, so we need to allow the plugins we need in the root `composer.json` for the site that gets setup, which is the purview of https://github.com/deviantintegral/drupal_tests IIRC. 

The Drupal site for testing is setup via Docker:

https://github.com/deviantintegral/drupal_tests/blob/master/Dockerfile#L112

If we were to rebuild that Docker image it would probably fail with the same error.

So unless I'm overthinking this somehow (entirely possible, currently fueld by coffee and sugar :baby:), yeah... not fairly straightforward. I'd like to say a PR is incoming, but I may need to find some dedicated time first.

**Comment by deviantintegral** [comment]
In the short term, can we pin composer to a 2.1 release?

**Comment by dzmitrykruchko-nbcuni** [comment]
I think we need to rebuild that Docker image. But first created a PR with some updates to Dockerfile: https://github.com/deviantintegral/drupal_tests/pull/68

Just FYI: Composer 2.3.9 has the following fix [Release 2.3.9 · composer/composer](https://github.com/composer/composer/releases/tag/2.3.9) "Fixed allow-plugins BC mode to ensure old lock files created pre-2.2 can be installed with only a warning but plugins fully loaded". I played with it locally, and `composer create-project` works fine, it just gives a warning. However, `docker build` still fails for some reason at this `RUN` https://github.com/deviantintegral/drupal_tests/blob/master/Dockerfile#L117 , so that's why we need to explicitly allow those plugins.

**Comment by m4olivei** [comment]
Discussed offline, in summary:

* We're going to move development to drupal.org. Maintenance of `drupal_tests` has proven difficult in the past. It's again become stale (needs update to Drupal 9 and soon 10).
* We'll loose Behat tests, `drupal-check` job and code coverage with code climate. There are no Behat tests here anyways. We could potentially add back `drupal-check` on Drupal CI ([ref](https://www.drupal.org/drupalorg/docs/drupal-ci/customizing-drupalci-testing-for-projects)), and I haven't seen much value in code climate since I've been maintaining this module
* I've pushed the latest on the `8.x-1.x` branch to drupal.org
* I've turned on tests on the Drupal project. Currently having issues, will file an issue for that, where this issue will carry forward.
* Once we've resolved tests, we'll tag a release on Drupal.org. We've been using this module at NBC for years now with success, and will continue using and maintaining it.

**Comment by m4olivei** [comment]
Closing in favor of https://www.drupal.org/project/media_mpx/issues/3306914
