### ISSUE TITLE
Add a class to iframes for behaviours to use

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/media_mpx#33]
We need to support behaviours on iframes, so custom code can react to player events. To do that, we need appropriate classes on the iframes so they can be selected with behaviours.

We should also document in the README how to implement a behaviour and respond to a player event.

**Comment by geekygnr** [comment]
@deviantintegral I put in a couple of initial classes based on a guess of the kind of identifiers that would be needed (See https://github.com/Lullabot/media_mpx/tree/iframe-classes).

My initial thought was:

```
'mpx-iframe',
'mpx-iframe-account--' . $source_plugin->getAccount()->id(),
```
The only other thing I could think of added was one with the pid of the media object so there is something identifying the specific object. I haven't done that yet since it sounds like there are better ways to identify things based on other discussions we have had.

One thing I noticed while trying to identify what you wanted in the README and if there was anything else I should do to support the use of behaviours I found this which suggests an HTML5 player should be possible. Looking at our implementation I found that the there is an option under the advanced settings tab. I haven't tested to avoid doing something I shouldn't but it looks like you can prioritize HTML over flash.
https://docs.theplatform.com/help/players-embed-players-using-iframe-elements

As for the behaviours, I am not 100% what to document but I found this. Is this the behaviour you would like documented to the README and if so are there any rules around disclosure I should be aware of? https://docs.theplatform.com/help/player-using-the-external-controller

**Comment by deviantintegral** [comment]
I like the idea of per-account classes, though I'd probably use the machine name of the account config entity instead.

`iframe` in the class name seems redundant. How about just `mpx-player` and `mpx-player-account--<machine_name>`?

Yes, HTML5 players are not only possible but used in most cases. However, there is still an iframe that is used to host whatever player is being returned.

I was referring to Drupal behaviours - just so that developers can know we add those classes without having to go splunking through the code to find them.

**Comment by geekygnr** [comment]
Pull request created
