### ISSUE TITLE
Investigate splitting \Drupal\media_mpx\Commands\MpxImporter

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/media_mpx#82]
Following up from #81 .

This class has 5 constructor arguments, which is a sign of it getting too complex. However, it's not a simple refactor as the parameters are all used by all the drush commands.

**Comment by salvamomo** [comment]
This class has been refactored a bit recently and only has 4 constructor arguments.

I believe we could simplify it further and have a cleaner structure if we remove the `warmCache` command:

1. It's not something one would expect to find in an `MpxImporter` command class.
2. It'd allow us to remove the `DataObjectFactoryCreator` depending from our constructor, since the recent refactor already removed that dependency from the `import` command.

This would result in a new command class in a separate file, like `MpxCacheWarmer` or similar.
